name: obs_command
description: A sample command-line application for obs.
version: 1.1.0
homepage: https://github.com/Sabuto/obs_command-dart
issue_tracker: https://github.com/Sabuto/obs_command-dart/issues
documentation: https://github.com/Sabuto/obs_command-dart/blob/v1.0.0/README.md

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies:
  args: ^2.1.1
  obs_websocket: ^2.2.6
  yaml: ^3.1.0

