on:
  create:
  push:
    branches:
      - master


name: Build and Release Apps
jobs:
  build:
    name: Run tests and analyze code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
      - name: Install pub Dependencies
        run: dart pub get
      - name: Analyze code
        run: dart analyze
      - name: Run Tests
        run: dart test

  artifacts:
    needs: build
    name: Build binaries and Create release if tagged
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        include:
          - os: ubuntu-latest
            output-name: obs_command-linux
          - os: macOS-latest
            output-name: obs_command-mac
          - os: windows-latest
            output-name: obs_command-windows.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
      - name: Install pub Dependencies
        run: dart pub get
      - name: Make build dir
        run: mkdir build
      - name: Build Artifacts
        run: dart compile exe -o build/${{matrix.output-name}} bin/obs_command.dart
      - name: Upload native

        uses: actions/upload-artifact@v1
        with:
          name: native-executeables
          path: build

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: native-executeables
      - name: Create Release
        id: release_drafter
        uses: release-drafter/release-drafter@v5.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Upload Release Asset - linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_drafter.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: /home/runner/work/obs_command-dart/obs_command-dart/obs_command-linux
          asset_name: obs_command-linux
          asset_content_type: application/octet-stream
      - name: Upload Release Asset - windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_drafter.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: /home/runner/work/obs_command-dart/obs_command-dart/obs_command-windows.exe
          asset_name: obs_command-windows.exe
          asset_content_type: application/octet-stream
      - name: Upload Release Asset - windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_drafter.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: /home/runner/work/obs_command-dart/obs_command-dart/obs_command-mac
          asset_name: obs_command-mac
          asset_content_type: application/octet-stream
#      - name: Get release notes
#        run: echo ${{steps.release_notes.outputs.changelog}}
#      - name: Create Release
#        uses: softprops/action-gh-release@v1
#        with:
#          draft: true
#          body: ${{steps.release_notes.outputs.changelog}}
#          files: |
#            /home/runner/work/obs_command-dart/obs_command-dart/obs_command-linux
#            /home/runner/work/obs_command-dart/obs_command-dart/obs_command-mac
#            /home/runner/work/obs_command-dart/obs_command-dart/obs_command-windows.exe
#        env:
#          GITHUB_TOKEN: ${{secrets.TOKEN}}

