on:
  create:
  push:
    branches:
      - master


name: Build and Release Apps
jobs:
  build:
    name: Run tests and analyze code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
      - name: Install pub Dependencies
        run: dart pub get
      - name: Analyze code
        run: dart analyze
      - name: Run Tests
        run: dart test

  artifacts:
    needs: build
    name: Build binaries and Create release if tagged
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        include:
          - os: ubuntu-latest
            output-name: obs_command-linux
          - os: macOS-latest
            output-name: obs_command-mac
          - os: windows-latest
            output-name: obs_command-windows.exe

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Dart
        uses: dart-lang/setup-dart@v1
      - name: Install pub Dependencies
        run: dart pub get
      - name: Make build dir
        run: mkdir build
      - name: Build Artifacts
        run: dart compile exe -o build/${{matrix.output-name}} bin/obs_command.dart
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: native-executeables
          path: build

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: native-executeables
      - name: Create Release Notes
        id: release_notes
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Get release notes
        run: echo "${{setps.release_notes.outputs.changelog}}"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          body: ${{steps.release_notes.outputs.changelog}}
          files: |
            /home/runner/work/obs_command-dart/obs_command-dart/obs_command-linux
            /home/runner/work/obs_command-dart/obs_command-dart/obs_command-mac
            /home/runner/work/obs_command-dart/obs_command-dart/obs_command-windows.exe
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}